prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2
prisma:query SELECT 1
prisma:query SELECT "public"."MarketingModal"."id", "public"."MarketingModal"."active", "public"."MarketingModal"."title", "public"."MarketingModal"."subtitle", "public"."MarketingModal"."description", "public"."MarketingModal"."imageUrl", "public"."MarketingModal"."ctaText", "public"."MarketingModal"."ctaLink", "public"."MarketingModal"."ctaType", "public"."MarketingModal"."timerEnabled", "public"."MarketingModal"."timerLabel", "public"."MarketingModal"."timerEnd", "public"."MarketingModal"."position", "public"."MarketingModal"."delayMs", "public"."MarketingModal"."createdAt", "public"."MarketingModal"."updatedAt" FROM "public"."MarketingModal" WHERE "public"."MarketingModal"."active" = $1 LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Admin"."id", "public"."Admin"."email", "public"."Admin"."password", "public"."Admin"."name", "public"."Admin"."role", "public"."Admin"."createdAt", "public"."Admin"."updatedAt" FROM "public"."Admin" WHERE ("public"."Admin"."email" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2
prisma:query SELECT 1
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."slug", "public"."Destination"."name", "public"."Destination"."region", "public"."Destination"."description", "public"."Destination"."image", "public"."Destination"."highlights", "public"."Destination"."rating", "public"."Destination"."reviewCount", "public"."Destination"."priceFrom", "public"."Destination"."active", "public"."Destination"."order", "public"."Destination"."createdAt", "public"."Destination"."updatedAt" FROM "public"."Destination" WHERE 1=1 ORDER BY "public"."Destination"."order" ASC OFFSET $1
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."slug", "public"."Hotel"."name", "public"."Hotel"."cityId", "public"."Hotel"."cityName", "public"."Hotel"."stars", "public"."Hotel"."address", "public"."Hotel"."description", "public"."Hotel"."images", "public"."Hotel"."amenities", "public"."Hotel"."rooms", "public"."Hotel"."rating", "public"."Hotel"."reviewCount", "public"."Hotel"."priceFrom", "public"."Hotel"."tags", "public"."Hotel"."featured", "public"."Hotel"."active", "public"."Hotel"."createdAt", "public"."Hotel"."updatedAt" FROM "public"."Hotel" WHERE 1=1 OFFSET $1
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 OFFSET $1
prisma:query SELECT "public"."TransportService"."id", "public"."TransportService"."providerId", "public"."TransportService"."name", "public"."TransportService"."routeType", "public"."TransportService"."origin", "public"."TransportService"."destination", "public"."TransportService"."cityId", "public"."TransportService"."cityName", "public"."TransportService"."durationMins", "public"."TransportService"."basePrice", "public"."TransportService"."pricePerExtra", "public"."TransportService"."includes", "public"."TransportService"."notes", "public"."TransportService"."active", "public"."TransportService"."createdAt", "public"."TransportService"."updatedAt" FROM "public"."TransportService" WHERE 1=1 ORDER BY "public"."TransportService"."createdAt" DESC OFFSET $1
prisma:query SELECT "public"."TransportProvider"."id", "public"."TransportProvider"."name", "public"."TransportProvider"."legalName", "public"."TransportProvider"."nit", "public"."TransportProvider"."phone", "public"."TransportProvider"."email", "public"."TransportProvider"."vehicleType", "public"."TransportProvider"."capacity", "public"."TransportProvider"."active", "public"."TransportProvider"."createdAt", "public"."TransportProvider"."updatedAt", COALESCE("aggr_selection_0_TransportService"."_aggr_count_services", 0) AS "_aggr_count_services" FROM "public"."TransportProvider" LEFT JOIN (SELECT "public"."TransportService"."providerId", COUNT(*) AS "_aggr_count_services" FROM "public"."TransportService" WHERE 1=1 GROUP BY "public"."TransportService"."providerId") AS "aggr_selection_0_TransportService" ON ("public"."TransportProvider"."id" = "aggr_selection_0_TransportService"."providerId") WHERE 1=1 ORDER BY "public"."TransportProvider"."createdAt" DESC OFFSET $1
prisma:query SELECT "public"."MarketingModal"."id", "public"."MarketingModal"."active", "public"."MarketingModal"."title", "public"."MarketingModal"."subtitle", "public"."MarketingModal"."description", "public"."MarketingModal"."imageUrl", "public"."MarketingModal"."ctaText", "public"."MarketingModal"."ctaLink", "public"."MarketingModal"."ctaType", "public"."MarketingModal"."timerEnabled", "public"."MarketingModal"."timerLabel", "public"."MarketingModal"."timerEnd", "public"."MarketingModal"."position", "public"."MarketingModal"."delayMs", "public"."MarketingModal"."createdAt", "public"."MarketingModal"."updatedAt" FROM "public"."MarketingModal" WHERE 1=1 LIMIT $1 OFFSET $2
prisma:query INSERT INTO "public"."MarketingModal" ("id","active","title","subtitle","description","imageUrl","ctaText","ctaLink","ctaType","timerEnabled","timerLabel","position","delayMs","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING "public"."MarketingModal"."id", "public"."MarketingModal"."active", "public"."MarketingModal"."title", "public"."MarketingModal"."subtitle", "public"."MarketingModal"."description", "public"."MarketingModal"."imageUrl", "public"."MarketingModal"."ctaText", "public"."MarketingModal"."ctaLink", "public"."MarketingModal"."ctaType", "public"."MarketingModal"."timerEnabled", "public"."MarketingModal"."timerLabel", "public"."MarketingModal"."timerEnd", "public"."MarketingModal"."position", "public"."MarketingModal"."delayMs", "public"."MarketingModal"."createdAt", "public"."MarketingModal"."updatedAt"
prisma:query SELECT 1
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."slug", "public"."Hotel"."name", "public"."Hotel"."cityId", "public"."Hotel"."cityName", "public"."Hotel"."stars", "public"."Hotel"."address", "public"."Hotel"."description", "public"."Hotel"."images", "public"."Hotel"."amenities", "public"."Hotel"."rooms", "public"."Hotel"."rating", "public"."Hotel"."reviewCount", "public"."Hotel"."priceFrom", "public"."Hotel"."tags", "public"."Hotel"."featured", "public"."Hotel"."active", "public"."Hotel"."createdAt", "public"."Hotel"."updatedAt" FROM "public"."Hotel" WHERE 1=1 OFFSET $1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2
prisma:query SELECT 1
prisma:query SELECT "public"."MarketingModal"."id", "public"."MarketingModal"."active", "public"."MarketingModal"."title", "public"."MarketingModal"."subtitle", "public"."MarketingModal"."description", "public"."MarketingModal"."imageUrl", "public"."MarketingModal"."ctaText", "public"."MarketingModal"."ctaLink", "public"."MarketingModal"."ctaType", "public"."MarketingModal"."timerEnabled", "public"."MarketingModal"."timerLabel", "public"."MarketingModal"."timerEnd", "public"."MarketingModal"."position", "public"."MarketingModal"."delayMs", "public"."MarketingModal"."createdAt", "public"."MarketingModal"."updatedAt" FROM "public"."MarketingModal" WHERE "public"."MarketingModal"."active" = $1 LIMIT $2 OFFSET $3
prisma:query SELECT "public"."MarketingModal"."id", "public"."MarketingModal"."active", "public"."MarketingModal"."title", "public"."MarketingModal"."subtitle", "public"."MarketingModal"."description", "public"."MarketingModal"."imageUrl", "public"."MarketingModal"."ctaText", "public"."MarketingModal"."ctaLink", "public"."MarketingModal"."ctaType", "public"."MarketingModal"."timerEnabled", "public"."MarketingModal"."timerLabel", "public"."MarketingModal"."timerEnd", "public"."MarketingModal"."position", "public"."MarketingModal"."delayMs", "public"."MarketingModal"."createdAt", "public"."MarketingModal"."updatedAt" FROM "public"."MarketingModal" WHERE "public"."MarketingModal"."active" = $1 LIMIT $2 OFFSET $3
prisma:query SELECT 1
prisma:query SELECT "public"."Admin"."id", "public"."Admin"."email", "public"."Admin"."password", "public"."Admin"."name", "public"."Admin"."role", "public"."Admin"."createdAt", "public"."Admin"."updatedAt" FROM "public"."Admin" WHERE ("public"."Admin"."email" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT 1
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TransportService"."id" FROM "public"."TransportService" WHERE "public"."TransportService"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Excursion"."id" FROM "public"."Excursion" WHERE "public"."Excursion"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Hotel"."id" FROM "public"."Hotel" WHERE "public"."Hotel"."featured" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."soldOut" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."TravelPackage"."id" FROM "public"."TravelPackage" WHERE "public"."TravelPackage"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT COUNT(*) AS "_count$_all" FROM (SELECT "public"."Destination"."id" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2) AS "sub"
prisma:query SELECT "public"."Destination"."id", "public"."Destination"."rating" FROM "public"."Destination" WHERE "public"."Destination"."active" = $1 OFFSET $2
prisma:query SELECT "public"."Hotel"."id", "public"."Hotel"."rating" FROM "public"."Hotel" WHERE "public"."Hotel"."active" = $1 OFFSET $2
prisma:query SELECT "public"."TravelPackage"."id", "public"."TravelPackage"."slug", "public"."TravelPackage"."destinationId", "public"."TravelPackage"."destinationName", "public"."TravelPackage"."title", "public"."TravelPackage"."description", "public"."TravelPackage"."duration", "public"."TravelPackage"."price", "public"."TravelPackage"."originalPrice", "public"."TravelPackage"."includes", "public"."TravelPackage"."image", "public"."TravelPackage"."difficulty", "public"."TravelPackage"."groupSize", "public"."TravelPackage"."departureDates", "public"."TravelPackage"."rating", "public"."TravelPackage"."soldOut", "public"."TravelPackage"."category", "public"."TravelPackage"."commission", "public"."TravelPackage"."active", "public"."TravelPackage"."createdAt", "public"."TravelPackage"."updatedAt" FROM "public"."TravelPackage" WHERE 1=1 ORDER BY "public"."TravelPackage"."createdAt" DESC LIMIT $1 OFFSET $2