// ──────────────────────────────────────────────────────────────
// WILROP Colombia Travel — Database Seed Script
// Run with: bun run prisma/seed.ts
// ──────────────────────────────────────────────────────────────

import { PrismaClient } from '@prisma/client';
import { hashPassword } from '../src/lib/password.mjs';

const db = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ─── Clean existing data ─────────────────────────────────────
  await db.destinationCruise.deleteMany();
  await db.cruiseCabin.deleteMany();
  await db.cruise.deleteMany();
  await db.transportService.deleteMany();
  await db.transportProvider.deleteMany();
  await db.excursion.deleteMany();
  await db.travelPackage.deleteMany();
  await db.hotel.deleteMany();
  await db.destination.deleteMany();
  await db.admin.deleteMany();

  // ─── Admin user ──────────────────────────────────────────────
  await db.admin.create({
    data: {
      email: 'admin@wilrop.com',
      password: await hashPassword('admin123'),
      name: 'Administrador WILROP',
      role: 'admin',
    },
  });
  console.log('✅ Admin user created');

  // ─── Destinations ────────────────────────────────────────────
  const destinationData = [
    {
      slug: 'cartagena',
      name: 'Cartagena de Indias',
      region: 'Caribe',
      description: 'La joya colonial del Caribe colombiano. Ciudades amuralladas, playas paradisíacas y una vida nocturna vibrante te esperan en esta ciudad patrimonio de la humanidad.',
      image: '/images/cartagena.png',
      highlights: JSON.stringify(['Ciudad Amurallada', 'Playas del Bocagrande', 'Castillo San Felipe', 'Getsemaní']),
      rating: 4.8,
      reviewCount: 342,
      priceFrom: 870000,
      active: true,
      order: 0,
    },
    {
      slug: 'san-andres',
      name: 'San Andrés y Providencia',
      region: 'Caribe Insular',
      description: 'Un paraíso de aguas cristalinas en el mar Caribe. El archipiélago ofrece el mar de los siete colores, arrecifes de coral y una cultura raizal única.',
      image: '/images/san-andres.png',
      highlights: JSON.stringify(['Mar de 7 Colores', 'Johnny Cay', 'Raízal Culture', 'Buceo']),
      rating: 4.7,
      reviewCount: 285,
      priceFrom: 980000,
      active: true,
      order: 1,
    },
    {
      slug: 'medellin',
      name: 'Medellín',
      region: 'Andina',
      description: 'La ciudad de la eterna primavera. Innovación, cultura, gastronomía y transformación social en un valle rodeado de montañas verdes.',
      image: '/images/medellin.png',
      highlights: JSON.stringify(['Comuna 13', 'Pueblito Paisa', 'Jardín Botánico', 'Gastronomía']),
      rating: 4.6,
      reviewCount: 298,
      priceFrom: 620000,
      active: true,
      order: 2,
    },
    {
      slug: 'eje-cafetero',
      name: 'Eje Cafetero',
      region: 'Andina',
      description: 'El corazón del café colombiano. Haciendas cafeteras, paisajes verdes infinitos, pueblos pintorescos y la cultura del café que enamora al mundo.',
      image: '/images/eje-cafetero.png',
      highlights: JSON.stringify(['Haciendas Café', 'Salento', 'Valle del Cocora', 'Parque del Café']),
      rating: 4.9,
      reviewCount: 412,
      priceFrom: 550000,
      active: true,
      order: 3,
    },
    {
      slug: 'amazonia',
      name: 'Amazonía Colombiana',
      region: 'Orinoquía-Amazonía',
      description: 'La selva más grande del planeta. Una aventura inolvidable entre ríos caudalosos, fauna exótica y comunidades indígenas milenarias.',
      image: '/images/amazonia.png',
      highlights: JSON.stringify(['Río Amazonas', 'Dolphins Rosa', 'Maloca Indígena', 'Flora Exótica']),
      rating: 4.5,
      reviewCount: 156,
      priceFrom: 950000,
      active: true,
      order: 4,
    },
    {
      slug: 'bogota',
      name: 'Bogotá',
      region: 'Andina',
      description: 'La capital cosmopolita a 2.640 metros. Museos de clase mundial, gastronomía de autor, arte urbano y una oferta cultural inagotable.',
      image: '/images/bogota.png',
      highlights: JSON.stringify(['Museo del Oro', 'Cerro Monserrate', 'Candelaria', 'Gastronomía']),
      rating: 4.4,
      reviewCount: 223,
      priceFrom: 380000,
      active: true,
      order: 5,
    },
  ];

  for (const dest of destinationData) {
    await db.destination.create({ data: { ...dest, isTemplate: true } });
  }
  console.log(`✅ ${destinationData.length} destinations created`);

  // ─── Hotels ──────────────────────────────────────────────────
  const hotelData = [
    {
      slug: 'charleston-santa-teresa',
      name: 'Hotel Charleston Santa Teresa',
      cityId: 'cartagena',
      cityName: 'Cartagena de Indias',
      stars: 5,
      address: 'Calle de la Inquisición, Centro Histórico, Cartagena',
      description: 'Un hotel de lujo en el corazón del Centro Histórico de Cartagena, alojado en un exconvento del siglo XVII restaurado. Disfruta de la elegancia colonial combinada con comodidades modernas, una terraza con piscina infinita con vista a la ciudad amurallada, spa de clase mundial y gastronomía de autor.',
      images: JSON.stringify(['/images/cartagena.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'spa', 'ac', 'bar', 'reception', 'gym']),
      rooms: JSON.stringify([
        { id: 'cst-deluxe', name: 'Habitación Doble Deluxe', maxGuests: 2, beds: '1 cama king', price: 720000, originalPrice: 850000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Minibar'], available: 5, roomImage: '/images/cartagena.png' },
        { id: 'cst-suite', name: 'Suite Junior Colonial', maxGuests: 3, beds: '1 cama king + sofá cama', price: 850000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Minibar', 'Acceso spa'], available: 2, roomImage: '/images/cartagena.png' },
        { id: 'cst-master', name: 'Suite Master Terraza', maxGuests: 2, beds: '1 cama king', price: 1100000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Terraza privada', 'Jacuzzi', 'Acceso spa', 'Late check-out'], available: 1, roomImage: '/images/cartagena.png' },
      ]),
      rating: 9.2,
      reviewCount: 487,
      priceFrom: 720000,
      tags: JSON.stringify(['Lujo', 'Popular']),
      featured: true,
      active: true,
    },
    {
      slug: 'dann-carlton-medellin',
      name: 'Hotel Dann Carlton Medellín',
      cityId: 'medellin',
      cityName: 'Medellín',
      stars: 5,
      address: 'Carrera 43A # 7-50, El Poblado, Medellín',
      description: 'Ubicado en la exclusiva zona de El Poblado, este hotel de cinco estrellas ofrece una experiencia de lujo contemporáneo con las mejores vistas de la ciudad. Cuenta con restaurante gourmet, piscina rooftop, gimnasio completo y el servicio impecable que caracteriza a la cadena Dann Carlton.',
      images: JSON.stringify(['/images/medellin.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'gym', 'spa', 'ac', 'bar', 'reception']),
      rooms: JSON.stringify([
        { id: 'dc-standard', name: 'Habitación Estándar', maxGuests: 2, beds: '1 cama queen', price: 380000, originalPrice: 450000, includes: ['Desayuno americano', 'Wi-Fi gratis', 'Aire acondicionado'], available: 12, roomImage: '/images/medellin.png' },
        { id: 'dc-executive', name: 'Habitación Ejecutiva', maxGuests: 2, beds: '1 cama king', price: 520000, includes: ['Desayuno americano', 'Wi-Fi gratis', 'Sala ejecutiva', 'Aire acondicionado', 'Minibar'], available: 6, roomImage: '/images/medellin.png' },
        { id: 'dc-suite', name: 'Suite Ejecutiva', maxGuests: 3, beds: '1 cama king + sofá cama', price: 680000, includes: ['Desayuno americano', 'Wi-Fi gratis', 'Sala ejecutiva', 'Aire acondicionado', 'Minibar', 'Acceso piscina rooftop'], available: 3, roomImage: '/images/medellin.png' },
      ]),
      rating: 8.8,
      reviewCount: 623,
      priceFrom: 380000,
      tags: JSON.stringify(['Popular', 'Descuento']),
      featured: true,
      active: true,
    },
    {
      slug: 'decameron-isleno',
      name: 'Decameron Isleño',
      cityId: 'san-andres',
      cityName: 'San Andrés',
      stars: 4,
      address: 'Avenida Colón, Sector San Luis, San Andrés',
      description: 'El resort todo incluido más popular de San Andrés, ubicado frente al mar de los siete colores. Ofrece actividades acuáticas, entretenimiento diurno y nocturno, múltiples restaurantes y bares, piscina con vista al mar y acceso directo a la playa.',
      images: JSON.stringify(['/images/san-andres.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'bar', 'reception', 'ac', 'breakfast', 'sea-view']),
      rooms: JSON.stringify([
        { id: 'di-standard', name: 'Habitación Estándar Todo Incluido', maxGuests: 2, beds: '2 camas individuales', price: 450000, originalPrice: 520000, includes: ['Todo incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Actividades acuáticas'], available: 20, roomImage: '/images/san-andres.png' },
        { id: 'di-superior', name: 'Habitación Superior Vista al Mar', maxGuests: 2, beds: '1 cama queen', price: 580000, includes: ['Todo incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Vista al mar', 'Actividades acuáticas'], available: 8, roomImage: '/images/san-andres.png' },
        { id: 'di-junior-suite', name: 'Suite Junior Vista al Mar', maxGuests: 4, beds: '1 cama queen + 2 individuales', price: 720000, includes: ['Todo incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Vista al mar', 'Terraza', 'Late check-out'], available: 4, roomImage: '/images/san-andres.png' },
      ]),
      rating: 8.4,
      reviewCount: 892,
      priceFrom: 450000,
      tags: JSON.stringify(['Popular', 'Descuento']),
      featured: true,
      active: true,
    },
    {
      slug: 'sofitel-bogota',
      name: 'Hotel Sofitel Bogotá Victoria Regia',
      cityId: 'bogota',
      cityName: 'Bogotá',
      stars: 5,
      address: 'Carrera 13 # 85-46, Zona Rosa, Bogotá',
      description: 'En el exclusivo barrio de Zona Rosa, el Sofitel Victoria Regia combina la sofisticación francesa con el calor colombiano. Decoración elegante, restaurante de alta cocina, spa lujoso y ubicación privilegiada cerca de los mejores restaurantes y centros comerciales de la ciudad.',
      images: JSON.stringify(['/images/bogota.png']),
      amenities: JSON.stringify(['wifi', 'restaurant', 'parking', 'gym', 'spa', 'ac', 'bar', 'reception']),
      rooms: JSON.stringify([
        { id: 'sv-luxury', name: 'Habitación Lujo', maxGuests: 2, beds: '1 cama king', price: 650000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Minibar'], available: 7, roomImage: '/images/bogota.png' },
        { id: 'sv-prestige', name: 'Habitación Prestige Club', maxGuests: 2, beds: '1 cama king', price: 820000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Acceso Club Sofitel', 'Aperitivo nocturno', 'Aire acondicionado'], available: 3, roomImage: '/images/bogota.png' },
        { id: 'sv-suite-opera', name: 'Suite Opera', maxGuests: 3, beds: '1 cama king + sala separada', price: 1150000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Acceso Club Sofitel', 'Aperitivo nocturno', 'Spa', 'Late check-out', 'Transfer'], available: 1, roomImage: '/images/bogota.png' },
      ]),
      rating: 9.0,
      reviewCount: 356,
      priceFrom: 650000,
      tags: JSON.stringify(['Lujo', 'Nuevo']),
      featured: true,
      active: true,
    },
    {
      slug: 'irotama-resort',
      name: 'Irotama Resort',
      cityId: 'santa-marta',
      cityName: 'Santa Marta',
      stars: 4,
      address: 'Km 5 Vía a Rodadero, Santa Marta',
      description: 'El resort más emblemático de Santa Marta, con más de 40 años de tradición. Extensos jardines tropicales, 5 piscinas, restaurante frente al mar, spa y actividades para toda la familia.',
      images: JSON.stringify(['/images/eje-cafetero.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'gym', 'spa', 'ac', 'bar', 'reception', 'breakfast', 'transfer']),
      rooms: JSON.stringify([
        { id: 'ir-garden', name: 'Habitación Jardín', maxGuests: 2, beds: '1 cama queen', price: 340000, includes: ['Desayuno incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Piscinas'], available: 15, roomImage: '/images/eje-cafetero.png' },
        { id: 'ir-ocean', name: 'Habitación Vista al Mar', maxGuests: 2, beds: '1 cama queen', price: 480000, originalPrice: 560000, includes: ['Desayuno incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Vista al mar', 'Piscinas'], available: 8, roomImage: '/images/eje-cafetero.png' },
        { id: 'ir-bungalow', name: 'Bungalow Familiar', maxGuests: 5, beds: '1 cama queen + 2 individuales + sofá cama', price: 650000, includes: ['Desayuno incluido', 'Wi-Fi gratis', 'Aire acondicionado', 'Terraza privada', 'Piscinas', 'Kids Club'], available: 4, roomImage: '/images/eje-cafetero.png' },
      ]),
      rating: 8.5,
      reviewCount: 745,
      priceFrom: 340000,
      tags: JSON.stringify(['Popular']),
      featured: false,
      active: true,
    },
    {
      slug: 'casa-adobe',
      name: 'Hotel Casa de Adobe',
      cityId: 'villa-de-leyva',
      cityName: 'Villa de Leyva',
      stars: 3,
      address: 'Calle 12 # 11-65, Villa de Leyva',
      description: 'Un encantador hotel boutique construido en adobe y teja colonial, en el corazón de Villa de Leyva. Sus patios interiores con jardines, chimeneas y decoración rústica te transportan a otra época.',
      images: JSON.stringify(['/images/amazonia.png']),
      amenities: JSON.stringify(['wifi', 'restaurant', 'parking', 'ac', 'breakfast', 'reception']),
      rooms: JSON.stringify([
        { id: 'ca-standard', name: 'Habitación Colonial', maxGuests: 2, beds: '1 cama matrimonial', price: 220000, includes: ['Desayuno casero', 'Wi-Fi gratis', 'Chimenea'], available: 6, roomImage: '/images/amazonia.png' },
        { id: 'ca-deluxe', name: 'Habitación Deluxe con Chimenea', maxGuests: 2, beds: '1 cama queen', price: 320000, includes: ['Desayuno casero', 'Wi-Fi gratis', 'Chimenea', 'Vista al jardín', 'Bañera'], available: 3, roomImage: '/images/amazonia.png' },
      ]),
      rating: 8.9,
      reviewCount: 234,
      priceFrom: 220000,
      tags: JSON.stringify(['Nuevo']),
      featured: false,
      active: true,
    },
    {
      slug: 'hotel-spiwak',
      name: 'Hotel Spiwak Chipichape',
      cityId: 'cali',
      cityName: 'Cali',
      stars: 4,
      address: 'Carrera 38 Norte # 6N-100, Chipichape, Cali',
      description: 'Conectado directamente al centro comercial Chipichape, el Hotel Spiwak es la opción perfecta para viajeros de negocios y turismo. Modernas instalaciones, casino, restaurante de autor y piscina en la azotea.',
      images: JSON.stringify(['/images/hero.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'gym', 'spa', 'ac', 'bar', 'reception']),
      rooms: JSON.stringify([
        { id: 'sp-standard', name: 'Habitación Estándar', maxGuests: 2, beds: '1 cama queen', price: 290000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado'], available: 18, roomImage: '/images/hero.png' },
        { id: 'sp-executive', name: 'Habitación Ejecutiva', maxGuests: 2, beds: '1 cama king', price: 420000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Minibar', 'Acceso gym'], available: 9, roomImage: '/images/hero.png' },
        { id: 'sp-suite', name: 'Suite Spiwak', maxGuests: 3, beds: '1 cama king + sofá cama', price: 560000, originalPrice: 650000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Sala de estar', 'Acceso spa', 'Casino'], available: 3, roomImage: '/images/hero.png' },
      ]),
      rating: 8.6,
      reviewCount: 512,
      priceFrom: 290000,
      tags: JSON.stringify(['Descuento']),
      featured: false,
      active: true,
    },
    {
      slug: 'hacienda-bambusa',
      name: 'Hacienda Bambusa',
      cityId: 'pereira',
      cityName: 'Pereira (Eje Cafetero)',
      stars: 4,
      address: 'Km 7 Vía Cerritos, Pereira',
      description: 'Una auténtica hacienda cafetera transformada en hotel boutique rodeada de jardines tropicales y plantaciones de café. Experimenta la cultura del café desde su origen.',
      images: JSON.stringify(['/images/eje-cafetero.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'spa', 'breakfast', 'reception', 'transfer']),
      rooms: JSON.stringify([
        { id: 'hb-superior', name: 'Habitación Superior Cafetal', maxGuests: 2, beds: '1 cama queen', price: 350000, includes: ['Desayuno campesino', 'Wi-Fi gratis', 'Tour del café', 'Aire acondicionado'], available: 8, roomImage: '/images/eje-cafetero.png' },
        { id: 'hb-junior', name: 'Suite Junior Hacienda', maxGuests: 3, beds: '1 cama king + sofá cama', price: 480000, includes: ['Desayuno campesino', 'Wi-Fi gratis', 'Tour del café', 'Vista a los cafetales', 'Bañera de hidromasaje'], available: 4, roomImage: '/images/eje-cafetero.png' },
        { id: 'hb-master', name: 'Suite Master Bambusa', maxGuests: 2, beds: '1 cama king', price: 620000, includes: ['Desayuno campesino', 'Wi-Fi gratis', 'Tour del café', 'Terraza privada', 'Spa', 'Late check-out'], available: 2, roomImage: '/images/eje-cafetero.png' },
      ]),
      rating: 9.1,
      reviewCount: 289,
      priceFrom: 350000,
      tags: JSON.stringify(['Nuevo', 'Popular']),
      featured: false,
      active: true,
    },
    {
      slug: 'casa-quintero',
      name: 'Hotel Casa Quintero',
      cityId: 'cartagena',
      cityName: 'Cartagena de Indias',
      stars: 3,
      address: 'Calle Quintero # 3-42, Centro Histórico, Cartagena',
      description: 'Un encantador hotel boutique en una casona colonial restaurada del siglo XVIII, ubicada a pasos de la Plaza de los Coches.',
      images: JSON.stringify(['/images/cartagena.png']),
      amenities: JSON.stringify(['wifi', 'ac', 'breakfast', 'reception']),
      rooms: JSON.stringify([
        { id: 'cq-classic', name: 'Habitación Clásica Colonial', maxGuests: 2, beds: '1 cama matrimonial', price: 280000, includes: ['Desayuno cartagenero', 'Wi-Fi gratis', 'Aire acondicionado'], available: 5, roomImage: '/images/cartagena.png' },
        { id: 'cq-patio', name: 'Habitación con Vista al Patio', maxGuests: 2, beds: '1 cama queen', price: 380000, originalPrice: 440000, includes: ['Desayuno cartagenero', 'Wi-Fi gratis', 'Aire acondicionado', 'Vista al patio colonial', 'Terraza'], available: 3, roomImage: '/images/cartagena.png' },
      ]),
      rating: 8.7,
      reviewCount: 178,
      priceFrom: 280000,
      tags: JSON.stringify(['Descuento', 'Nuevo']),
      featured: false,
      active: true,
    },
    {
      slug: 'intercontinental-medellin',
      name: 'InterContinental Medellín',
      cityId: 'medellin',
      cityName: 'Medellín',
      stars: 5,
      address: 'Carrera 34 # 4A-15, Poblado, Medellín',
      description: 'El hotel de negocios por excelencia de Medellín, ubicado en la financial district con acceso directo al centro comercial Santafé.',
      images: JSON.stringify(['/images/medellin.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'gym', 'spa', 'ac', 'bar', 'reception', 'transfer']),
      rooms: JSON.stringify([
        { id: 'im-classic', name: 'Habitación Classic', maxGuests: 2, beds: '1 cama queen', price: 450000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Aire acondicionado', 'Centro de negocios'], available: 14, roomImage: '/images/medellin.png' },
        { id: 'im-club', name: 'Habitación Club InterContinental', maxGuests: 2, beds: '1 cama king', price: 620000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Club InterContinental', 'Aperitivo nocturno', 'Aire acondicionado'], available: 6, roomImage: '/images/medellin.png' },
        { id: 'im-suite', name: 'Suite Ejecutiva', maxGuests: 3, beds: '1 cama king + sofá cama', price: 780000, includes: ['Desayuno buffet', 'Wi-Fi gratis', 'Club InterContinental', 'Sala de estar', 'Spa', 'Transfer aeropuerto'], available: 2, roomImage: '/images/medellin.png' },
      ]),
      rating: 8.9,
      reviewCount: 421,
      priceFrom: 450000,
      tags: JSON.stringify(['Popular']),
      featured: false,
      active: true,
    },
    {
      slug: 'hotel-gaira',
      name: 'Hotel Gaira del Mar',
      cityId: 'santa-marta',
      cityName: 'Santa Marta',
      stars: 4,
      address: 'Vía a Riohacha Km 3, Taganga, Santa Marta',
      description: 'Ubicado entre la Sierra Nevada y el mar Caribe, este eco-resort ofrece una experiencia única de naturaleza y lujo.',
      images: JSON.stringify(['/images/san-andres.png']),
      amenities: JSON.stringify(['wifi', 'pool', 'restaurant', 'parking', 'ac', 'bar', 'reception', 'breakfast', 'sea-view']),
      rooms: JSON.stringify([
        { id: 'gm-ocean', name: 'Cabaña Vista al Mar', maxGuests: 2, beds: '1 cama queen', price: 390000, includes: ['Desayuno tropical', 'Wi-Fi gratis', 'Aire acondicionado', 'Vista al mar'], available: 7, roomImage: '/images/san-andres.png' },
        { id: 'gm-beachfront', name: 'Suite Frente al Mar', maxGuests: 3, beds: '1 cama king + sofá cama', price: 540000, originalPrice: 620000, includes: ['Desayuno tropical', 'Wi-Fi gratis', 'Aire acondicionado', 'Terraza frente al mar', 'Snorkel incluido'], available: 3, roomImage: '/images/san-andres.png' },
      ]),
      rating: 8.3,
      reviewCount: 198,
      priceFrom: 390000,
      tags: JSON.stringify(['Descuento']),
      featured: false,
      active: true,
    },
  ];

  for (const hotel of hotelData) {
    await db.hotel.create({ data: { ...hotel, isTemplate: true } });
  }
  console.log(`✅ ${hotelData.length} hotels created`);

  const transportProviders = [
    {
      data: {
        name: 'Wilrop Medellin Transfers',
        legalName: 'Willro Group Travel',
        nit: '',
        phone: '+57 300 000 0000',
        email: 'operaciones@willrogrouptravel.com',
        vehicleType: 'van',
        capacity: 6,
        active: true,
      },
      services: [
        {
          name: 'Traslado Aeropuerto MDE - Hotel Medellin',
          routeType: 'aeropuerto-hotel',
          origin: 'Aeropuerto Jose Maria Cordova',
          destination: 'Hotel en Medellin',
          cityId: 'medellin',
          cityName: 'Medellin',
          durationMins: 55,
          basePrice: 180000,
          pricePerExtra: 25000,
          includes: JSON.stringify(['Conductor privado', 'Equipaje', 'Seguimiento de vuelo']),
          notes: 'Producto terrestre base para paquetes con hoteles y excursiones de Medellin.',
          active: true,
        },
        {
          name: 'Traslado Hotel Medellin - Aeropuerto MDE',
          routeType: 'hotel-aeropuerto',
          origin: 'Hotel en Medellin',
          destination: 'Aeropuerto Jose Maria Cordova',
          cityId: 'medellin',
          cityName: 'Medellin',
          durationMins: 55,
          basePrice: 180000,
          pricePerExtra: 25000,
          includes: JSON.stringify(['Conductor privado', 'Equipaje', 'Confirmacion previa']),
          notes: 'Servicio de salida para completar paquete terrestre receptivo.',
          active: true,
        },
      ],
    },
    {
      data: {
        name: 'Wilrop Cartagena Transfers',
        legalName: 'Willro Group Travel',
        nit: '',
        phone: '+57 300 000 0000',
        email: 'operaciones@willrogrouptravel.com',
        vehicleType: 'suv',
        capacity: 4,
        active: true,
      },
      services: [
        {
          name: 'Traslado Aeropuerto CTG - Hotel Cartagena',
          routeType: 'aeropuerto-hotel',
          origin: 'Aeropuerto Rafael Nunez',
          destination: 'Hotel en Cartagena',
          cityId: 'cartagena',
          cityName: 'Cartagena',
          durationMins: 25,
          basePrice: 95000,
          pricePerExtra: 15000,
          includes: JSON.stringify(['Conductor privado', 'Equipaje', 'Asistencia en llegada']),
          notes: 'Producto administrable para venta B2C y paquetes terrestres B2B.',
          active: true,
        },
      ],
    },
  ];

  let transportServiceCount = 0;
  for (const provider of transportProviders) {
    const createdProvider = await db.transportProvider.create({ data: { ...provider.data, isTemplate: true } });
    for (const service of provider.services) {
      await db.transportService.create({
        data: {
          providerId: createdProvider.id,
          ...service,
          isTemplate: true,
        },
      });
      transportServiceCount += 1;
    }
  }
  console.log(`✅ ${transportProviders.length} transport providers and ${transportServiceCount} services created`);

  // ─── Excursions ───────────────────────────────────────────────
  const excursionData = [
    {
      slug: 'comuna-13-grafiti-transformacion',
      name: 'Comuna 13: Grafiti y Transformacion Social',
      destinationId: 'medellin',
      destinationName: 'Medellin',
      cityName: 'Medellin',
      description: 'Recorrido guiado por escaleras electricas, murales y miradores de la Comuna 13, pensado como producto terrestre base para agencias y grupos receptivos.',
      shortDesc: 'Tour urbano por grafitis, historia local y miradores de Medellin.',
      images: JSON.stringify(['/images/medellin.png']),
      duration: '4 horas',
      difficulty: 'Facil',
      groupSize: '2 - 20 personas',
      basePrice: 120000,
      childPrice: 90000,
      includes: JSON.stringify(['Guia local', 'Recorrido grafiti', 'Snack local', 'Asistencia Willro']),
      excludes: JSON.stringify(['Almuerzo', 'Propinas', 'Gastos personales']),
      requirements: JSON.stringify(['Calzado comodo', 'Documento de identidad']),
      category: 'Cultural',
      rating: 4.8,
      featured: true,
      active: true,
    },
    {
      slug: 'guatape-piedra-penol-dia-completo',
      name: 'Guatape y Piedra del Penol',
      destinationId: 'medellin',
      destinationName: 'Medellin',
      cityName: 'Guatape',
      description: 'Excursion de dia completo desde Medellin hacia Guatape, con visita a la Piedra del Penol, malecon y recorrido por zocalos tradicionales.',
      shortDesc: 'Dia completo a Guatape con Penol, malecon y pueblo de zocalos.',
      images: JSON.stringify(['/images/medellin.png']),
      duration: '10 horas',
      difficulty: 'Moderado',
      groupSize: '2 - 18 personas',
      basePrice: 230000,
      childPrice: 180000,
      includes: JSON.stringify(['Transporte compartido', 'Guia acompanante', 'Almuerzo tipico', 'Seguro de asistencia']),
      excludes: JSON.stringify(['Entrada a la Piedra del Penol', 'Bebidas no descritas']),
      requirements: JSON.stringify(['Calzado comodo', 'Bloqueador solar', 'Chaqueta ligera']),
      category: 'Naturaleza',
      rating: 4.9,
      featured: true,
      active: true,
    },
    {
      slug: 'city-tour-medellin-pueblito-paisa',
      name: 'City Tour Medellin y Pueblito Paisa',
      destinationId: 'medellin',
      destinationName: 'Medellin',
      cityName: 'Medellin',
      description: 'Producto urbano para complementar paquetes con hoteles aliados: visita panoramica por Medellin, Pueblito Paisa y puntos representativos.',
      shortDesc: 'Recorrido panoramico para completar paquetes terrestres en Medellin.',
      images: JSON.stringify(['/images/medellin.png']),
      duration: '5 horas',
      difficulty: 'Facil',
      groupSize: '2 - 20 personas',
      basePrice: 150000,
      childPrice: 110000,
      includes: JSON.stringify(['Transporte local', 'Guia acompanante', 'Paradas fotograficas']),
      excludes: JSON.stringify(['Almuerzo', 'Entradas no descritas']),
      requirements: JSON.stringify(['Calzado comodo']),
      category: 'Cultural',
      rating: 4.7,
      featured: false,
      active: true,
    },
  ];

  for (const excursion of excursionData) {
    await db.excursion.create({ data: { ...excursion, isTemplate: true } });
  }
  console.log(`✅ ${excursionData.length} excursions created`);

  // ─── Travel Packages ─────────────────────────────────────────
  const packageData = [
    {
      slug: 'cartagena-romantico',
      destinationId: 'cartagena',
      destinationName: 'Cartagena de Indias',
      title: 'Cartagena Romántica',
      description: 'Un escape romántico por la Ciudad Amurallada: paseos en coche de caballos, cenas al atardecer frente al mar, tour privado por el Castillo San Felipe y un día en las Islas del Rosario.',
      duration: '4 días / 3 noches',
      price: 1250000,
      originalPrice: 1480000,
      includes: JSON.stringify(['Alojamiento en hotel boutique 4★', 'Desayuno buffet diario', 'Tour privado Ciudad Amurallada', 'Visita Castillo San Felipe', 'Paseo en coche de caballos', 'Excursión Isla del Rosario', 'Traslados aeropuerto – hotel']),
      image: '/images/cartagena.png',
      difficulty: 'Fácil',
      groupSize: '2 – 8 personas',
      departureDates: JSON.stringify(['2025-07-15', '2025-08-10', '2025-09-05', '2025-10-12', '2025-11-20']),
      rating: 4.9,
      soldOut: false,
      category: 'Relax',
      commission: 12,
      active: true,
    },
    {
      slug: 'cartagena-cultural',
      destinationId: 'cartagena',
      destinationName: 'Cartagena de Indias',
      title: 'Cartagena Cultural e Histórica',
      description: 'Sumérgete en la historia de Cartagena con visitas guiadas a museos, bazares de artesanías, clases de cocina caribeña y exploración de los barrios históricos de Getsemaní y La Matuna.',
      duration: '5 días / 4 noches',
      price: 1450000,
      includes: JSON.stringify(['Alojamiento en hotel colonial 4★', 'Desayuno diario + 2 almuerzos', 'Tour histórico guiado completo', 'Taller de cocina caribeña', 'Visita al Museo Naval y Palacio de la Inquisición', 'Recorrido por Getsemaní', 'Traslados aeropuerto – hotel']),
      image: '/images/cartagena.png',
      difficulty: 'Fácil',
      groupSize: '4 – 12 personas',
      departureDates: JSON.stringify(['2025-07-22', '2025-08-18', '2025-09-15', '2025-10-08']),
      rating: 4.7,
      soldOut: false,
      category: 'Cultural',
      commission: 10,
      active: true,
    },
    {
      slug: 'medellin-innovacion',
      destinationId: 'medellin',
      destinationName: 'Medellín',
      title: 'Medellín: Innovación y Cultura Urbana',
      description: 'Descubre la transformación de Medellín: tours por la Comuna 13, recorrido en Metrocable hasta el Parque Arví, visita a museos de arte moderno y las mejores miradores de la ciudad.',
      duration: '4 días / 3 noches',
      price: 980000,
      originalPrice: 1100000,
      includes: JSON.stringify(['Alojamiento en hotel 4★ en Poblado', 'Desayuno buffet diario', 'Tour Comuna 13 – grafiti y transformación', 'Metrocable + Parque Arví', 'Tour ciudad y museos (MAMM, Casa de la Memoria)', 'Visita a Guatapé y Piedra del Peñol', 'Traslados aeropuerto – hotel']),
      image: '/images/medellin.png',
      difficulty: 'Fácil',
      groupSize: '4 – 15 personas',
      departureDates: JSON.stringify(['2025-07-10', '2025-08-05', '2025-09-02', '2025-10-15', '2025-11-08']),
      rating: 4.8,
      soldOut: false,
      category: 'Cultural',
      commission: 12,
      active: true,
    },
    {
      slug: 'medellin-aventura',
      destinationId: 'medellin',
      destinationName: 'Medellín',
      title: 'Aventura Paisa',
      description: 'Para los más intrépidos: canopy en Santa Fe de Antioquia, rafting en el río San Juan, parapente sobre el Valle de Aburrá y senderismo en los cerros del oriente.',
      duration: '3 días / 2 noches',
      price: 870000,
      includes: JSON.stringify(['Alojamiento en hotel 3★', 'Desayuno diario', 'Canopy en Santa Fe de Antioquia', 'Rafting río San Juan (nivel II–III)', 'Vuelo en parapente doble', 'Traslados desde Medellín']),
      image: '/images/medellin.png',
      difficulty: 'Moderado',
      groupSize: '6 – 12 personas',
      departureDates: JSON.stringify(['2025-07-20', '2025-08-15', '2025-09-25']),
      rating: 4.6,
      soldOut: true,
      category: 'Aventura',
      commission: 15,
      active: true,
    },
    {
      slug: 'san-andres-playa',
      destinationId: 'san-andres',
      destinationName: 'San Andrés y Providencia',
      title: 'Paraíso en el Caribe – Todo Incluido',
      description: 'Disfruta del mar de los siete colores con un paquete todo incluido: snorkel en el cinturón de coral, tours a Cayo Acuario y Johnny Cay, gastronomía raizal y atardeceres inolvidables.',
      duration: '5 días / 4 noches',
      price: 1680000,
      originalPrice: 1950000,
      includes: JSON.stringify(['Alojamiento resort todo incluido 4★', 'Todas las comidas y bebidas', 'Tour Cayo Acuario', 'Tour Johnny Cay', 'Snorkel en arrecife', 'Tour isla en golf cart', 'Traslados aeropuerto – hotel']),
      image: '/images/san-andres.png',
      difficulty: 'Fácil',
      groupSize: '2 – 10 personas',
      departureDates: JSON.stringify(['2025-07-18', '2025-08-08', '2025-09-12', '2025-10-20', '2025-11-15', '2025-12-10']),
      rating: 4.9,
      soldOut: false,
      category: 'Playa',
      commission: 10,
      active: true,
    },
    {
      slug: 'san-andres-buceo',
      destinationId: 'san-andres',
      destinationName: 'San Andrés y Providencia',
      title: 'Buceo y Naturaleza en Providencia',
      description: 'Una expedición para amantes del buceo: immersiones en el tercer arrecife más grande del mundo, exploración de la isla de Providencia y contacto con la cultura raizal auténtica.',
      duration: '6 días / 5 noches',
      price: 2150000,
      includes: JSON.stringify(['Alojamiento en hotel boutique frente al mar', 'Desayuno diario + 3 cenas', '5 buceos con equipo incluido (PADI Open Water)', 'Tour en lancha por los cayos', 'Visita a Crab Cay y McBean Lagoon', 'Traslado en catamarán San Andrés → Providencia', 'Seguro de viaje']),
      image: '/images/san-andres.png',
      difficulty: 'Moderado',
      groupSize: '4 – 8 personas',
      departureDates: JSON.stringify(['2025-08-20', '2025-09-22', '2025-10-25']),
      rating: 4.8,
      soldOut: false,
      category: 'Naturaleza',
      commission: 14,
      active: true,
    },
    {
      slug: 'eje-cafetero-experiencia',
      destinationId: 'eje-cafetero',
      destinationName: 'Eje Cafetero',
      title: 'Experiencia Cafetera Completa',
      description: 'Vive el proceso del café desde la semilla hasta la taza. Visita haciendas centenarias, explora el Valle del Cocora, disfruta de termales y conoce los pueblos más hermosos de Quindío y Risaralda.',
      duration: '5 días / 4 noches',
      price: 1120000,
      originalPrice: 1300000,
      includes: JSON.stringify(['Alojamiento en hacienda cafetera tradicional', 'Desayuno tipo casero + 2 almuerzos', 'Tour finca cafetera (proceso completo + catación)', 'Valle del Cocora + Salento', 'Termales de Santa Rosa de Cabal', 'Visita a Filandia y pueblo de los Artistas', 'Traslados desde Pereira / Armenia']),
      image: '/images/eje-cafetero.png',
      difficulty: 'Fácil',
      groupSize: '4 – 12 personas',
      departureDates: JSON.stringify(['2025-07-12', '2025-08-02', '2025-09-10', '2025-10-05', '2025-11-18']),
      rating: 4.9,
      soldOut: false,
      category: 'Cultural',
      commission: 12,
      active: true,
    },
    {
      slug: 'eje-cafetero-aventura',
      destinationId: 'eje-cafetero',
      destinationName: 'Eje Cafetero',
      title: 'Aventura en los Andes Cafeteros',
      description: 'Senderismo entre palmas de cera, canopy sobre cañones, rafting en el río La Vieja y ciclismo de montaña por los paisajes del Eje Cafetero.',
      duration: '4 días / 3 noches',
      price: 950000,
      includes: JSON.stringify(['Alojamiento en eco-lodge', 'Desayuno + 2 almuerzos', 'Trekking Valle del Cocora (6 h)', 'Canopy Parque del Café', 'Rafting río La Vieja (nivel III)', 'Bicicleta de montaña por fincas', 'Traslados desde Armenia']),
      image: '/images/eje-cafetero.png',
      difficulty: 'Avanzado',
      groupSize: '6 – 10 personas',
      departureDates: JSON.stringify(['2025-07-25', '2025-09-08', '2025-10-20']),
      rating: 4.7,
      soldOut: true,
      category: 'Aventura',
      commission: 15,
      active: true,
    },
    {
      slug: 'amazonia-inmersion',
      destinationId: 'amazonia',
      destinationName: 'Amazonía Colombiana',
      title: 'Inmersión Amazónica',
      description: 'Adéntrate en la selva con una expedición de 4 días: avistamiento de delfines rosados, caminatas nocturnas, pesca piranha, visita a comunidades indígenas y pernocta en maloca tradicional.',
      duration: '4 días / 3 noches',
      price: 1650000,
      includes: JSON.stringify(['Alojamiento en maloca amazónica', 'Todas las comidas (cocina local)', 'Traslado Leticia – comunidad (canoa)', 'Avistamiento de delfines rosados', 'Caminata nocturna en la selva', 'Pesca de piraña', 'Visita a comunidad Tikuna', 'Guía nativo bilingüe']),
      image: '/images/amazonia.png',
      difficulty: 'Moderado',
      groupSize: '4 – 8 personas',
      departureDates: JSON.stringify(['2025-08-01', '2025-09-15', '2025-10-20', '2025-11-10']),
      rating: 4.8,
      soldOut: false,
      category: 'Naturaleza',
      commission: 14,
      active: true,
    },
    {
      slug: 'amazonia-exploracion',
      destinationId: 'amazonia',
      destinationName: 'Amazonía Colombiana',
      title: 'Expedición Profunda al Amazonas',
      description: 'Para los aventureros más exigentes: una semana en la selva virgen navegando el río Amazonas, campamento en la jungla, avistamiento de fauna mayor y convivencia con comunidades remotas.',
      duration: '7 días / 6 noches',
      price: 2850000,
      originalPrice: 3200000,
      includes: JSON.stringify(['Alojamiento (hostal 2 noches + camping 3 noches + maloca 1 noche)', 'Todas las comidas', 'Navegación río Amazonas y afluentes', 'Camping en selva virgen', 'Avistamiento de fauna (monos, anacondas, aves)', 'Talleres de supervivencia y plantas medicinales', 'Visita a 2 comunidades indígenas', 'Guía experto + guía nativo', 'Seguro de expedición']),
      image: '/images/amazonia.png',
      difficulty: 'Avanzado',
      groupSize: '4 – 6 personas',
      departureDates: JSON.stringify(['2025-09-01', '2025-11-05']),
      rating: 4.9,
      soldOut: false,
      category: 'Aventura',
      commission: 15,
      active: true,
    },
    {
      slug: 'bogota-gourmet',
      destinationId: 'bogota',
      destinationName: 'Bogotá',
      title: 'Bogotá Gourmet y Bohemia',
      description: 'Un recorrido por los sabores y la cultura de la capital: mercados locales, restaurantes galardonados, barrios bohemios, museos y la mejor vista desde el Cerro de Monserrate.',
      duration: '3 días / 2 noches',
      price: 780000,
      includes: JSON.stringify(['Alojamiento en hotel 4★ (La Candelaria / Zona G)', 'Desayuno diario', 'Tour gastronómico (Mercado de Paloquemao + Zona G)', 'Visita Museo del Oro', 'Cerro de Monserrate (teleférico)', 'Recorrido por La Candelaria', 'Traslados aeropuerto – hotel']),
      image: '/images/bogota.png',
      difficulty: 'Fácil',
      groupSize: '4 – 10 personas',
      departureDates: JSON.stringify(['2025-07-08', '2025-07-25', '2025-08-15', '2025-09-10', '2025-10-05', '2025-11-12', '2025-12-03']),
      rating: 4.7,
      soldOut: false,
      category: 'Cultural',
      commission: 8,
      active: true,
    },
    {
      slug: 'bogota-chingaza',
      destinationId: 'bogota',
      destinationName: 'Bogotá',
      title: 'Chingaza y los Páramos Andinos',
      description: 'Explora el Parque Nacional Natural Chingaza, hogar del oso de anteojos y los frailejones. Caminatas por el páramo, lagunas de origen glaciar y experiencias de turismo rural.',
      duration: '2 días / 1 noche',
      price: 620000,
      includes: JSON.stringify(['Alojamiento en finca rural', 'Desayuno + almuerzo + cena', 'Trekking Parque Chingaza (5 h)', 'Visita a lagunas glaciar', 'Charla sobre ecosistema páramo', 'Transporte desde Bogotá (ida y vuelta)']),
      image: '/images/bogota.png',
      difficulty: 'Moderado',
      groupSize: '6 – 12 personas',
      departureDates: JSON.stringify(['2025-07-30', '2025-08-22', '2025-09-28']),
      rating: 4.6,
      soldOut: false,
      category: 'Naturaleza',
      commission: 12,
      active: true,
    },
  ];

  for (const pkg of packageData) {
    await db.travelPackage.create({ data: { ...pkg, isTemplate: true } });
  }
  console.log(`✅ ${packageData.length} travel packages created`);

  // ─── Cruises ──────────────────────────────────────────────────
  const cartagena = await db.destination.findUnique({ where: { slug: 'cartagena' } });
  const sanAndres = await db.destination.findUnique({ where: { slug: 'san-andres' } });

  const cruiseData = [
    {
      slug: 'caribe-premium',
      name: 'Caribe Premium',
      description: 'Disfruta de una experiencia de crucero inolvidable navegando por las aguas turquesas del Caribe. Este crucero incluye shows en vivo, múltiples piscinas, restaurantes buffet y a la carta, y paradas de ensueño.',
      shipName: 'Monarch of the Seas',
      operator: 'Pullmantur',
      durationDays: 5,
      images: JSON.stringify(['/images/cruceros.png']),
      includes: JSON.stringify(['Pensión completa', 'Bebidas ilimitadas', 'Acceso a shows', 'Piscinas', 'Gimnasio']),
      itinerary: JSON.stringify([
        { day: 1, stop: 'Cartagena (Embarque)' },
        { day: 2, stop: 'Navegación' },
        { day: 3, stop: 'San Andrés (Parada)' },
        { day: 4, stop: 'Navegación' },
        { day: 5, stop: 'Cartagena (Desembarque)' },
      ]),
      rating: 4.8,
      reviewCount: 145,
      priceFrom: 2350000,
      tags: JSON.stringify(['Premium', 'Popular']),
      featured: true,
      active: true,
      primaryDestinationId: cartagena?.id,
      cabins: [
        { name: 'Camarote Interior Estándar', capacity: 2, beds: '2 camas individuales', basePrice: 2350000, originalPrice: 2800000, includes: JSON.stringify(['Servicio de limpieza diario', 'TV satelital', 'Wi-Fi prepagado']), cabinImage: '/images/cruceros.png' },
        { name: 'Camarote Exterior con Vista al Mar', capacity: 2, beds: '1 cama doble', basePrice: 2950000, originalPrice: 3500000, includes: JSON.stringify(['Ventana al océano', 'Servicio de limpieza diario', 'TV satelital', 'Wi-Fi prepagado']), cabinImage: '/images/cruceros.png' },
        { name: 'Suite de Lujo con Balcón', capacity: 3, beds: '1 cama doble king + sofá cama', basePrice: 4200000, includes: JSON.stringify(['Balcón privado', 'Acceso preferente', 'Servicio a la habitación 24/7', 'Minibar premium']), cabinImage: '/images/cruceros.png' },
      ],
      destinationIds: [cartagena?.id, sanAndres?.id].filter(Boolean) as string[],
    },
    {
      slug: 'san-andres-express',
      name: 'San Andrés Express',
      description: 'Una escapada rápida para explorar los cayos y arrecifes de coral en los alrededores de la isla de San Andrés.',
      shipName: 'Sea Explorer',
      operator: 'Caribbean Cruises',
      durationDays: 3,
      images: JSON.stringify(['/images/cruceros.png']),
      includes: JSON.stringify(['Alojamiento a bordo', 'Desayuno y almuerzo buffet', 'Actividades de snorkel']),
      itinerary: JSON.stringify([
        { day: 1, stop: 'San Andrés (Embarque)' },
        { day: 2, stop: 'Johnny Cay y Haynes Cay' },
        { day: 3, stop: 'San Andrés (Desembarque)' },
      ]),
      rating: 4.5,
      reviewCount: 82,
      priceFrom: 1450000,
      tags: JSON.stringify(['Express']),
      featured: false,
      active: true,
      primaryDestinationId: sanAndres?.id,
      cabins: [
        { name: 'Camarote Estándar Vista al Mar', capacity: 2, beds: '2 camas individuales', basePrice: 1450000, originalPrice: 1800000, includes: JSON.stringify(['TV satelital', 'Aire acondicionado']), cabinImage: '/images/cruceros.png' },
      ],
      destinationIds: [sanAndres?.id].filter(Boolean) as string[],
    },
    {
      slug: 'islas-del-rosario-day-cruise',
      name: 'Islas del Rosario Day Cruise',
      description: 'Pasa un día espectacular navegando a bordo de nuestro exclusivo catamarán. Disfruta de barra libre nacional, almuerzo típico y desembarque en playa privada.',
      shipName: 'Catamarán Bora Bora',
      operator: 'Bora Bora S.A.',
      durationDays: 1,
      images: JSON.stringify(['/images/cruceros.png']),
      includes: JSON.stringify(['Barra libre nacional', 'Almuerzo típico', 'Equipos de snorkel', 'Acceso a playa privada']),
      itinerary: JSON.stringify([
        { day: 1, stop: 'Muelle de Cartagena (Salida: 8:00 AM) -> Recorrido Islas del Rosario -> Playa Privada -> Retorno Cartagena (5:00 PM)' },
      ]),
      rating: 4.7,
      reviewCount: 210,
      priceFrom: 680000,
      tags: JSON.stringify(['Day Cruise', 'Nuevo']),
      featured: false,
      active: true,
      primaryDestinationId: cartagena?.id,
      cabins: [
        { name: 'Pase de Pasadía Estándar', capacity: 1, beds: 'Asiento reservado', basePrice: 680000, includes: JSON.stringify(['Coctel de bienvenida', 'Almuerzo tradicional']), cabinImage: '/images/cruceros.png' },
      ],
      destinationIds: [cartagena?.id].filter(Boolean) as string[],
    },
  ];

  for (const cruise of cruiseData) {
    const { cabins, destinationIds, ...cruiseFields } = cruise;
    const createdCruise = await db.cruise.create({
      data: {
        ...cruiseFields,
        isTemplate: true,
        cabins: {
          create: cabins.map((c) => ({
            ...c,
            includes: c.includes,
          })),
        },
      },
    });

    for (const destinationId of destinationIds) {
      await db.destinationCruise.create({
        data: {
          destinationId,
          cruiseId: createdCruise.id,
          active: true,
        },
      });
    }
  }

  console.log(`✅ ${cruiseData.length} cruises created`);

  console.log('\n🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
